// Define reducer types here
export const GET_ERRS = 'GET_ERRS';
export const SET_SIGNED_IN_USER = 'SET_SIGNED_IN_USER';
export const GET_PT_CLIENTS_DATA = 'GET_PT_CLIENTS_DATA';
export const GET_PT_PROFILE = 'GET_PT_PROFILE';
export const GET_CURRENT_CLIENT = 'GET_CURRENT_CLIENT';
export const GET_CLIENT_PROFILE = 'GET_CLIENT_PROFILE';
export const PASSWORD_ERROR = 'PASSWORD_ERROR';
export const PT_CLIENT_PROGRESSION = 'PT_CLIENT_PROGRESSION';
export const CLIENT_PROGRESSION = 'CLIENT_PROGRESSION';
export const CLEAR_PROGRESSION = 'CLEAR_PROGRESSION';
export const SUCCESS = 'SUCCESS';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const CLEAR_CURRENT_CLIENT = 'CLEAR_CURRENT_CLIENT';
export const CLEAR_CLIENT_PROFILE = 'CLEAR_CLIENT_PROFILE';
export const SCHEDULER = 'SCHEDULER';
export const CLEAR_WORKOUT_DATA = 'CLEAR_WORKOUT_DATA';


